NOTION_API_KEY = "your_notion_api_key"
NOTION_DATABASE_ID = "your_notion_database_id"
TELEGRAM_API_KEY = "your_telegram_api_key"
OPENAI_API_KEY = "your_openai_api_key"
OPENAI_PROMPT = "your_openai_api_prompt"